---
- name: "Create the config path"
  file:
    path: "/etc/osquery_exporter"
    state: "directory"
    owner: "root"
    group: "root"
    mode: "u=rx,g=rx,o=rwx"

- name: "Create the systemd service"
  template:
    src: "etc/osquery_exporter/config.yml.j2"
    dest: "/etc/osquery_exporter/config.yml"
    owner: "root"
    mode: "u=rwx,g=r,o=r"
  notify: "restart osquery_exporter"

- name: "Check whether the node exporter has already been installed"
  stat:
    path: "/usr/local/bin/osquery_exporter"
    checksum_algorithm: "{{ osquery_exporter.checksum.algorithm }}"
  register: "bin"

- name: "Move node-exporter to the /usr/local/bin/node-exporter"
  copy:
    src: "{{ lookup('env', 'GOPATH') }}/bin/osquery_exporter"
    dest: "/usr/local/bin/osquery_exporter"
    owner: "root"
    group: "root"
    mode: "u=rwx,g=rwx,o=rwx"
  when: bin.stat.exists == False or
        bin.stat.checksum != "{{ osquery_exporter.checksum.binary }}"
  notify: "restart osquery_exporter"
